// Helper: generate the current expected-snapshots.ts from the live engine.
// Run once whenever the intended math changes: npx tsx src/lib/capture-snapshots.ts
import { simulate, malaysiaPreset, conservativePreset, leanFirePreset, noTopUpPreset, type SimInput } from "./sim";

const presets: [string, () => SimInput][] = [
  ["aggressive", malaysiaPreset],
  ["conservative", conservativePreset],
  ["leanFire", leanFirePreset],
  ["noTopUp", noTopUpPreset],
];

const r = Math.round;
const lines: string[] = [
  "// AUTO-GENERATED by src/lib/capture-snapshots.ts. Do not edit by hand.",
  "// Edit the engine, run `npx tsx src/lib/capture-snapshots.ts`, then commit.",
  "export const EXPECTED_SNAPSHOTS: Record<string, {",
  "  peakAge: number; peakAssets: number;",
  "  runsOutAtAge: number | null;",
  "  perAge: Record<number, { total: number; income: number; spend: number; drained: number; surplus: number; surplusSaved: number }>;",
  "}> = {",
];

for (const [key, fn] of presets) {
  const result = simulate(fn());
  lines.push(`  ${key}: {`);
  lines.push(`    peakAge: ${result.peakAge},`);
  lines.push(`    peakAssets: ${r(result.peakAssets)},`);
  lines.push(`    runsOutAtAge: ${result.runsOutAtAge ?? "null"},`);
  lines.push(`    perAge: {`);
  for (const row of result.rows) {
    lines.push(
      `      ${row.age}: { total: ${r(row.totalAssets)}, income: ${r(row.income)}, ` +
      `spend: ${r(row.totalSpend)}, drained: ${r(row.portfolioDrained)}, ` +
      `surplus: ${r(row.surplus)}, surplusSaved: ${r(row.surplusSaved)} },`
    );
  }
  lines.push(`    },`);
  lines.push(`  },`);
}

lines.push("};");
const out = lines.join("\n") + "\n";

// Write to expected-snapshots.ts
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, "expected-snapshots.ts");
writeFileSync(target, out);
console.log(`Wrote ${target} (${out.length} bytes)`);
